In [5]:
# Imports
from src.color_space.all import *
from matplotlib import pyplot as plt
size: int = 2

In [3]:
# Ask user for image size to generate
size: int = int(input("Enter the size of the image to generate: "))

In [6]:
# Generate a random image and plot it
sliced: np.ndarray = random_image(size, seed = 0, maxi = 5)
r_image: np.ndarray = sliced_rgb_to_img(sliced)
print(sliced)
print(r_image)
#plt.imshow(r_image)

[[[4 0 3]
  [3 3 1]
  [3 2 4]]

 [[0 0 4]
  [2 1 0]
  [1 1 0]]

 [[1 4 3]
  [0 3 0]
  [2 3 0]]]
[[[4 0 1]
  [0 0 4]
  [3 4 3]]

 [[3 2 0]
  [3 1 3]
  [1 0 0]]

 [[3 1 2]
  [2 1 3]
  [4 0 0]]]


In [7]:
# Niveaux de gris
converters = [rgb_to_grayscale_average, rgb_to_grayscale_norm709, rgb_to_grayscale_norm601]
for f in converters:
	img = f(sliced)
	#plt.figure()
	print(img)
	#plt.imshow(sliced_rgb_to_img(img), cmap = 'gray')
	#plt.title(f.__name__)

[[1.66666667 1.33333333 3.33333333]
 [1.66666667 2.33333333 0.33333333]
 [2.         2.         1.33333333]]
[[0.9221 0.2884 3.7154]
 [2.0683 1.5692 0.2125]
 [1.4971 1.3567 0.85  ]]
[[1.31  0.456 3.587]
 [2.071 1.826 0.299]
 [1.712 1.527 1.196]]


In [8]:
## Linears
converters = [rgb_to_yiq, rgb_to_yuv, rgb_to_i1i2i3, rgb_to_rgb_normalized]
for f in converters:
	img = f(sliced)
	#plt.figure()
	print(img)
	#plt.imshow(sliced_rgb_to_img(img))
	#plt.title(f.__name__)

[[ 1.407  0.844  3.914]
 [ 1.213 -0.082  0.587]
 [ 0.644  0.842  0.456]]
[[ 1.811  2.46   2.154]
 [ 1.183 -0.073  0.587]
 [ 0.579  0.365  0.456]]
[[ 1.08333333 -1.          2.25      ]
 [ 1.          2.5         0.33333333]
 [ 0.         -0.58333333  1.33333333]]
[[[0.8        0.         0.3       ]
  [0.6        0.42857143 1.        ]
  [0.5        0.33333333 1.        ]]

 [[0.         0.         0.4       ]
  [0.4        0.14285714 0.        ]
  [0.16666667 0.16666667 0.        ]]

 [[0.2        1.         0.3       ]
  [0.         0.42857143 0.        ]
  [0.33333333 0.5        0.        ]]]
